
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rduuurfysvqwhpyyadux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkdXV1cmZ5c3Zxd2hweXlhZHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDY0NDAsImV4cCI6MjA2MDE4MjQ0MH0.VHp2zSXGn51YRvb-csZWNS8NmwSU9ORl2G_s4Q3X_3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
